name: Format and Lint
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Checks
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - run: pip install --upgrade pip
      - run: pip install pipenv
      - run: pipenv install
      - run: pipenv shell
      - run: python black --diff --check $(git ls-files '*.py')
      - run: python pylint --disable=all --enable=unused-import $(git ls-files '*.py')
      - run: python mypy --strict $(git ls-files '*.py')
